version: '3'
services:
  website:
    image: php:apache
    depends_on:
      - api
    ports:
      - "5001:80"
    environment:
      - USERNAME=user
      - PASSWORD=password
    volumes:
      - ./website:/var/www/html

  api:
    build: ./simple_api
    volumes: 
      - ./simple_api:/data/

    ports:
      - "5000:80"
